package com.cyrillrx.family.group.domain

import kotlin.jvm.JvmInline
import kotlin.uuid.Uuid

/** Identifies a group. Every shared record carries one. */
@JvmInline
value class GroupId(val value: String)

/**
 * Identifies a member. This is ours, not the authentication provider's: the credential that
 * authenticates a member is held beside it, in [Member.credentialId]. See ADR-003 — conflating
 * the two would make leaving the provider destroy every member's identity.
 */
@JvmInline
value class MemberId(val value: String)

/** Identifies an invitation. Distinct from the invitation's secret code. */
@JvmInline
value class InvitationId(val value: String)

/**
 * Produces the identifiers of newly created records.
 *
 * Identifiers are generated by the client rather than assigned by the store, so the identifier
 * space belongs to the product and not to whichever provider currently holds the data (ADR-003).
 * Tests substitute an implementation that counts instead of randomising.
 */
interface IdGenerator {
    fun newGroupId(): GroupId

    fun newMemberId(): MemberId

    fun newInvitationId(): InvitationId
}

/** The production [IdGenerator]: random version-4 UUIDs, from the Kotlin standard library. */
object UuidIdGenerator : IdGenerator {
    override fun newGroupId(): GroupId = GroupId(Uuid.random().toString())

    override fun newMemberId(): MemberId = MemberId(Uuid.random().toString())

    override fun newInvitationId(): InvitationId = InvitationId(Uuid.random().toString())
}
